version: '3.7'

services:
  
  rabbitmq:
    image: "rabbitmq:3.8.5-management-alpine"
    ports:
      - "15672:15672"
      #- "5672:5672"
      - "5671:5671"
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "./certificates/rootca/:/etc/rabbitmq/certs/rootca/"
      - "./certificates/rabbitmq/:/etc/rabbitmq/certs/rabbitmq/"
      - "./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro"
      - "./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro"
      - "./rabbitmq/erlang.cookie:/var/lib/rabbitmq/mnesia/.erlang.cookie"

  consumer: 
    build: ./rabbitmq-consumer
    volumes:
      - "./certificates/rootca/rootCA.crt:/usr/local/share/certificates/rootCA.crt"
      - "./certificates/consumer/consumer.p12:/app/consumer.p12"
      - "./certificates/rootca/rootCA.crt:/app/rootCA.crt"
    depends_on: 
      - rabbitmq

  producer: 
    build: ./rabbitmq-producer
    volumes:
      - "./certificates/rootca/rootCA.crt:/usr/local/share/certificates/rootCA.crt"
      - "./certificates/producer/producer.p12:/app/producer.p12"
      - "./certificates/rootca/rootCA.crt:/app/rootCA.crt"
    depends_on: 
      - rabbitmq